"""initial schema - core (users/roles/permissions/audit/settings) + fleet (vehicles/trips/reservations/defects/services/documents/notifications)

Revision ID: 0001
Revises:
Create Date: 2026-09-16

Vytváří obě schémata (core = uživatelé/role/audit/nastavení, fleet =
vozový park) a naplní role a oprávnění. Aplikace je po `alembic upgrade
head` připravená k použití, chybí jen první admin - viz
scripts/create_admin.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Oprávnění (zadání 4). Kódy jsou to, na co se ptá app/core/deps.py a
# app/core/access.py - držet je v jednom seznamu, ne rozeseté po routách.
PERMISSIONS = [
    ("core.user.manage", "Správa uživatelů a jejich rolí"),
    ("fleet.vehicle.view", "Zobrazení vozidel a jejich stavu"),
    ("fleet.vehicle.create", "Založení nového vozidla"),
    ("fleet.vehicle.manage", "Správa jakéhokoliv vozidla (administrátor)"),
    ("fleet.vehicle.manage.own", "Správa svěřených vozidel (odpovědná osoba)"),
    ("fleet.trip.create", "Zahájení a ukončení vlastní výpůjčky"),
    ("fleet.trip.manage", "Administrativní zásah do jízd (oprava, zrušení)"),
    ("fleet.reservation.create", "Vytvoření vlastní rezervace"),
    ("fleet.reservation.manage", "Správa cizích rezervací a servisních bloků"),
    ("fleet.defect.report", "Nahlášení závady"),
    ("fleet.defect.manage", "Řešení závad a změna jejich stavu"),
    ("fleet.logbook.view", "Kniha jízd napříč vozidly včetně exportů"),
    ("fleet.settings.manage", "Nastavení aplikace (prahy upozornění)"),
]

# Řidič - to, co zadání 4 vyjmenovává jako „běžný uživatel". Nesmí měnit
# konfiguraci vozidla, servis ani dokumenty.
USER_PERMISSIONS = {
    "fleet.vehicle.view", "fleet.trip.create", "fleet.reservation.create", "fleet.defect.report",
}
# Odpovědná osoba - řidič + plná správa VLASTNÍCH vozidel. Rozsah "jen
# moje vozidla" nezajišťuje role, ale fleet.vehicle.manage.own porovnané
# proti vehicle.responsible_user_id (app/core/access.py).
RESPONSIBLE_PERMISSIONS = USER_PERMISSIONS | {
    "fleet.vehicle.manage.own", "fleet.defect.manage", "fleet.logbook.view",
}

ROLES = [
    ("admin", "Administrátor - úplný přístup"),
    ("odpovedna_osoba", "Odpovědná osoba - správce svěřených vozidel"),
    ("user", "Řidič - výpůjčky, rezervace, závady"),
]


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS fleet")
    # Kvůli EXCLUDE constraintu níž: gist index nad uuid sloupcem
    # (vehicle_id) umí jen btree_gist.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key'),
    schema='core'
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['core.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission'),
    schema='core'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role'),
    schema='core'
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('tank_capacity_l', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_token', sa.String(length=32), nullable=False),
    sa.Column('current_odometer_km', sa.Integer(), nullable=False),
    sa.Column('current_fuel_level', sa.Integer(), nullable=True),
    sa.Column('state_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stk_valid_until', sa.Date(), nullable=True),
    sa.Column('vignette_valid_until', sa.Date(), nullable=True),
    sa.Column('insurance_company', sa.String(length=255), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_valid_until', sa.Date(), nullable=True),
    sa.Column('last_oil_change_at', sa.Date(), nullable=True),
    sa.Column('last_oil_change_km', sa.Integer(), nullable=True),
    sa.Column('oil_interval_km', sa.Integer(), nullable=True),
    sa.Column('oil_interval_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_code'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_vehicles_qr_token'), 'vehicles', ['qr_token'], unique=True, schema='fleet')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_notifications_dedupe_key'), 'notifications', ['dedupe_key'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_notifications_vehicle_id'), 'notifications', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expected_route', sa.Text(), nullable=True),
    sa.Column('expected_km', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_fleet_reservations_end_after_start'),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_reservations_user_id'), 'reservations', ['user_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_reservations_vehicle_id'), 'reservations', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('vehicle_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('vehicle_services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('price_czk', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_vehicle_services_vehicle_id'), 'vehicle_services', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('trips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('primary_driver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_odometer_km', sa.Integer(), nullable=False),
    sa.Column('end_odometer_km', sa.Integer(), nullable=True),
    sa.Column('start_fuel_level', sa.Integer(), nullable=True),
    sa.Column('end_fuel_level', sa.Integer(), nullable=True),
    sa.Column('purpose_code', sa.String(length=30), nullable=True),
    sa.Column('purpose_text', sa.String(length=255), nullable=True),
    sa.Column('route_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('reservation_conflict_id', sa.UUID(), nullable=True),
    sa.Column('reservation_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_distance_km', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('distance_diff_percent', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('distance_explanation', sa.Text(), nullable=True),
    sa.Column('started_by', sa.UUID(), nullable=True),
    sa.Column('ended_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_odometer_km IS NULL OR end_odometer_km >= start_odometer_km', name='ck_fleet_trips_end_km_not_lower'),
    sa.ForeignKeyConstraint(['ended_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_driver_id'], ['core.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_conflict_id'], ['fleet.reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['fleet.reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_trips_primary_driver_id'), 'trips', ['primary_driver_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False, schema='fleet')
    op.create_index('uq_fleet_trips_one_active_per_vehicle', 'trips', ['vehicle_id'], unique=True, schema='fleet', postgresql_where=sa.text("status = 'active'"))
    op.create_table('trip_drivers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index('uq_fleet_trip_drivers_unique', 'trip_drivers', ['trip_id', 'user_id'], unique=True, schema='fleet')
    op.create_table('trip_fuelings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('fueled_at', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('price_total_czk', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_unit_czk', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('station', sa.String(length=255), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ocr_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("unit IN ('l', 'kWh')", name='ck_fleet_fuelings_unit'),
    sa.CheckConstraint('quantity > 0', name='ck_fleet_fuelings_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_trip_fuelings_trip_id'), 'trip_fuelings', ['trip_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_trip_fuelings_vehicle_id'), 'trip_fuelings', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('trip_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet.trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_trip_notes_trip_id'), 'trip_notes', ['trip_id'], unique=False, schema='fleet')
    op.create_table('vehicle_defects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet.trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_vehicle_defects_vehicle_id'), 'vehicle_defects', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('defect_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('fueling_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=False),
    sa.Column('full_path', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['defect_id'], ['fleet.vehicle_defects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fueling_id'], ['fleet.trip_fuelings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['fleet.vehicle_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_attachments_defect_id'), 'attachments', ['defect_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_attachments_fueling_id'), 'attachments', ['fueling_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_attachments_service_id'), 'attachments', ['service_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_attachments_trip_id'), 'attachments', ['trip_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_attachments_vehicle_id'), 'attachments', ['vehicle_id'], unique=False, schema='fleet')

    # --- rezervace se nesmí překrývat -----------------------------------
    # Dvě aktivní rezervace jednoho vozidla na překrývající se čas nesmí
    # vzniknout ani při dvou souběžných requestech. Kontrola v aplikaci
    # (SELECT + INSERT) má mezi dotazem a zápisem okno, ve kterém projdou
    # obě; tohle je jediná záruka, která to zavírá. Plain UNIQUE index
    # překryv rozsahů vyjádřit neumí - proto EXCLUDE.
    # Zrušené a naplněné rezervace se neúčastní (WHERE status = 'active'),
    # takže zrušený termín okamžitě uvolní místo.
    op.execute(
        """
        ALTER TABLE fleet.reservations
        ADD CONSTRAINT ex_fleet_reservations_no_overlap
        EXCLUDE USING gist (
            vehicle_id WITH =,
            tstzrange(start_at, end_at) WITH &&
        ) WHERE (status = 'active')
        """
    )

    # --- role a oprávnění -------------------------------------------------
    conn = op.get_bind()
    permission_ids = {}
    for code, description in PERMISSIONS:
        permission_ids[code] = conn.execute(
            sa.text("INSERT INTO core.permissions (code, description) VALUES (:code, :description) RETURNING id"),
            {"code": code, "description": description},
        ).scalar_one()

    role_ids = {}
    for name, description in ROLES:
        role_ids[name] = conn.execute(
            sa.text("INSERT INTO core.roles (name, description) VALUES (:name, :description) RETURNING id"),
            {"name": name, "description": description},
        ).scalar_one()

    def grant(role: str, codes) -> None:
        for code in sorted(codes):
            conn.execute(
                sa.text(
                    "INSERT INTO core.role_permissions (role_id, permission_id) "
                    "VALUES (:role_id, :permission_id)"
                ),
                {"role_id": role_ids[role], "permission_id": permission_ids[code]},
            )

    grant("admin", permission_ids.keys())
    grant("odpovedna_osoba", RESPONSIBLE_PERMISSIONS)
    grant("user", USER_PERMISSIONS)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fleet_attachments_vehicle_id'), table_name='attachments', schema='fleet')
    op.drop_index(op.f('ix_fleet_attachments_trip_id'), table_name='attachments', schema='fleet')
    op.drop_index(op.f('ix_fleet_attachments_service_id'), table_name='attachments', schema='fleet')
    op.drop_index(op.f('ix_fleet_attachments_fueling_id'), table_name='attachments', schema='fleet')
    op.drop_index(op.f('ix_fleet_attachments_defect_id'), table_name='attachments', schema='fleet')
    op.drop_table('attachments', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_defects_vehicle_id'), table_name='vehicle_defects', schema='fleet')
    op.drop_table('vehicle_defects', schema='fleet')
    op.drop_index(op.f('ix_fleet_trip_notes_trip_id'), table_name='trip_notes', schema='fleet')
    op.drop_table('trip_notes', schema='fleet')
    op.drop_index(op.f('ix_fleet_trip_fuelings_vehicle_id'), table_name='trip_fuelings', schema='fleet')
    op.drop_index(op.f('ix_fleet_trip_fuelings_trip_id'), table_name='trip_fuelings', schema='fleet')
    op.drop_table('trip_fuelings', schema='fleet')
    op.drop_index('uq_fleet_trip_drivers_unique', table_name='trip_drivers', schema='fleet')
    op.drop_table('trip_drivers', schema='fleet')
    op.drop_index('uq_fleet_trips_one_active_per_vehicle', table_name='trips', schema='fleet', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_fleet_trips_vehicle_id'), table_name='trips', schema='fleet')
    op.drop_index(op.f('ix_fleet_trips_primary_driver_id'), table_name='trips', schema='fleet')
    op.drop_table('trips', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_services_vehicle_id'), table_name='vehicle_services', schema='fleet')
    op.drop_table('vehicle_services', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_documents_vehicle_id'), table_name='vehicle_documents', schema='fleet')
    op.drop_table('vehicle_documents', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments', schema='fleet')
    op.drop_table('vehicle_assignments', schema='fleet')
    op.drop_index(op.f('ix_fleet_reservations_vehicle_id'), table_name='reservations', schema='fleet')
    op.drop_index(op.f('ix_fleet_reservations_user_id'), table_name='reservations', schema='fleet')
    op.drop_table('reservations', schema='fleet')
    op.drop_index(op.f('ix_fleet_notifications_vehicle_id'), table_name='notifications', schema='fleet')
    op.drop_index(op.f('ix_fleet_notifications_user_id'), table_name='notifications', schema='fleet')
    op.drop_index(op.f('ix_fleet_notifications_dedupe_key'), table_name='notifications', schema='fleet')
    op.drop_table('notifications', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicles_qr_token'), table_name='vehicles', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicles_license_plate'), table_name='vehicles', schema='fleet')
    op.drop_table('vehicles', schema='fleet')
    op.drop_table('user_roles', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('audit_log', schema='core')
    op.drop_table('app_settings', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_table('roles', schema='core')
    op.drop_table('permissions', schema='core')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS fleet")
    op.execute("DROP SCHEMA IF EXISTS core")
