"""pozadavky A-D: uprava casu jizdy, schvalovani vozidel, viditelnost

Požadavky A, B, D (viz docs/ROZHODNUTI.md):

- A) fleet.trips.times_edited_at / times_edited_by - opravený čas jízdy
  se nesmí tvářit jako původně naměřený.
- B) fleet.trip_requests + fleet.vehicles.approval_required +
  fleet.trips.request_id - schvalovací workflow pro vybraná vozidla.
- D) fleet.vehicles.visibility - vozidlo viditelné všem, nebo jen
  odpovědné osobě a administrátorovi.

Požadavek C (náhledová fotografie) schéma neměnil - náhled je první
existující Attachment s kind="vehicle_photo".

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-16 23:13:05.263983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('needed_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needed_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['core.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_trip_requests_requester_id'), 'trip_requests', ['requester_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_trip_requests_vehicle_id'), 'trip_requests', ['vehicle_id'], unique=False, schema='fleet')
    op.create_index('uq_fleet_trip_requests_one_pending', 'trip_requests', ['vehicle_id', 'requester_id'], unique=True, schema='fleet', postgresql_where=sa.text("status = 'pending'"))
    op.add_column('trips', sa.Column('times_edited_at', sa.DateTime(timezone=True), nullable=True), schema='fleet')
    op.add_column('trips', sa.Column('times_edited_by', sa.UUID(), nullable=True), schema='fleet')
    op.add_column('trips', sa.Column('request_id', sa.UUID(), nullable=True), schema='fleet')
    op.create_unique_constraint(None, 'trips', ['request_id'], schema='fleet')
    op.create_foreign_key(None, 'trips', 'trip_requests', ['request_id'], ['id'], source_schema='fleet', referent_schema='fleet', ondelete='SET NULL')
    op.create_foreign_key(None, 'trips', 'users', ['times_edited_by'], ['id'], source_schema='fleet', referent_schema='core', ondelete='SET NULL')
    # server_default kvůli existujícím řádkům; po naplnění se zahodí, aby
    # výchozí hodnota zůstala jen v modelu (jinak by se dvě místa
    # rozcházela). Výchozí stav zachovává dosavadní chování: vozidlo
    # nevyžaduje schválení a vidí ho každý.
    op.add_column(
        'vehicles',
        sa.Column('approval_required', sa.Boolean(), nullable=False, server_default=sa.false()),
        schema='fleet',
    )
    op.add_column(
        'vehicles',
        sa.Column('visibility', sa.String(length=20), nullable=False, server_default='all'),
        schema='fleet',
    )
    op.alter_column('vehicles', 'approval_required', server_default=None, schema='fleet')
    op.alter_column('vehicles', 'visibility', server_default=None, schema='fleet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'visibility', schema='fleet')
    op.drop_column('vehicles', 'approval_required', schema='fleet')
    op.drop_constraint(None, 'trips', schema='fleet', type_='foreignkey')
    op.drop_constraint(None, 'trips', schema='fleet', type_='foreignkey')
    op.drop_constraint(None, 'trips', schema='fleet', type_='unique')
    op.drop_column('trips', 'request_id', schema='fleet')
    op.drop_column('trips', 'times_edited_by', schema='fleet')
    op.drop_column('trips', 'times_edited_at', schema='fleet')
    op.drop_index('uq_fleet_trip_requests_one_pending', table_name='trip_requests', schema='fleet', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_fleet_trip_requests_vehicle_id'), table_name='trip_requests', schema='fleet')
    op.drop_index(op.f('ix_fleet_trip_requests_requester_id'), table_name='trip_requests', schema='fleet')
    op.drop_table('trip_requests', schema='fleet')
    # ### end Alembic commands ###
