"""kola pneumatiky a vydaje vozidla

Revision ID: cb8ec5862e32
Kola/pneumatiky a výdaje vozidla.

- fleet.wheel_sets: konkrétní sada kol (sezóna, výrobce, rozměr, DOT,
  dezén, pořízení). Rušení je soft delete - vyřazená sada nesmí zmizet
  z historie přezutí.
- fleet.wheel_fitments: historie nasazení. Částečný unikátní index
  zaručuje nejvýš jednu nasazenou sadu na vozidlo, i při souběhu.
- fleet.vehicle_expenses: výdaje. Tankování v rámci jízdy se sem
  NEpřepisuje, zůstává v trip_fuelings (viz ROZHODNUTI.md R27).
- vehicle_documents.service_id / expense_id: doklad k servisu nebo
  výdaji. Znovu použité úložiště, které už umí PDF, autorizované
  stahování i soft delete - žádný třetí mechanismus na soubory.
- attachments.wheel_set_id: fotografie sady.

Nic se nemaže ani nepřepisuje, jen přibývá.

Revises: 0002
Create Date: 2026-09-17 23:03:27.506097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('purchase_odometer_km', sa.Integer(), nullable=True),
    sa.Column('dot_code', sa.String(length=20), nullable=True),
    sa.Column('tread_depth_mm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_wheel_sets_vehicle_id'), 'wheel_sets', ['vehicle_id'], unique=False, schema='fleet')
    op.create_table('wheel_fitments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wheel_set_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('fitted_at', sa.Date(), nullable=False),
    sa.Column('fitted_odometer_km', sa.Integer(), nullable=False),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.Column('removed_odometer_km', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('removed_odometer_km IS NULL OR removed_odometer_km >= fitted_odometer_km', name='ck_fleet_wheel_fitments_km_not_lower'),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wheel_set_id'], ['fleet.wheel_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_wheel_fitments_vehicle_id'), 'wheel_fitments', ['vehicle_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_wheel_fitments_wheel_set_id'), 'wheel_fitments', ['wheel_set_id'], unique=False, schema='fleet')
    op.create_index('uq_fleet_wheel_fitments_one_active_per_vehicle', 'wheel_fitments', ['vehicle_id'], unique=True, schema='fleet', postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('vehicle_expenses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('expense_type', sa.String(length=30), nullable=False),
    sa.Column('amount_czk', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_net_czk', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_czk', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_czk >= 0', name='ck_fleet_expenses_amount_not_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['fleet.trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet.vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fleet'
    )
    op.create_index(op.f('ix_fleet_vehicle_expenses_expense_date'), 'vehicle_expenses', ['expense_date'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_vehicle_expenses_trip_id'), 'vehicle_expenses', ['trip_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_vehicle_expenses_vehicle_id'), 'vehicle_expenses', ['vehicle_id'], unique=False, schema='fleet')
    op.add_column('attachments', sa.Column('wheel_set_id', sa.UUID(), nullable=True), schema='fleet')
    op.create_index(op.f('ix_fleet_attachments_wheel_set_id'), 'attachments', ['wheel_set_id'], unique=False, schema='fleet')
    op.create_foreign_key(None, 'attachments', 'wheel_sets', ['wheel_set_id'], ['id'], source_schema='fleet', referent_schema='fleet', ondelete='CASCADE')
    op.add_column('vehicle_documents', sa.Column('service_id', sa.UUID(), nullable=True), schema='fleet')
    op.add_column('vehicle_documents', sa.Column('expense_id', sa.UUID(), nullable=True), schema='fleet')
    op.create_index(op.f('ix_fleet_vehicle_documents_expense_id'), 'vehicle_documents', ['expense_id'], unique=False, schema='fleet')
    op.create_index(op.f('ix_fleet_vehicle_documents_service_id'), 'vehicle_documents', ['service_id'], unique=False, schema='fleet')
    op.create_foreign_key(None, 'vehicle_documents', 'vehicle_expenses', ['expense_id'], ['id'], source_schema='fleet', referent_schema='fleet', ondelete='CASCADE')
    op.create_foreign_key(None, 'vehicle_documents', 'vehicle_services', ['service_id'], ['id'], source_schema='fleet', referent_schema='fleet', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_documents', schema='fleet', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_documents', schema='fleet', type_='foreignkey')
    op.drop_index(op.f('ix_fleet_vehicle_documents_service_id'), table_name='vehicle_documents', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_documents_expense_id'), table_name='vehicle_documents', schema='fleet')
    op.drop_column('vehicle_documents', 'expense_id', schema='fleet')
    op.drop_column('vehicle_documents', 'service_id', schema='fleet')
    op.drop_constraint(None, 'attachments', schema='fleet', type_='foreignkey')
    op.drop_index(op.f('ix_fleet_attachments_wheel_set_id'), table_name='attachments', schema='fleet')
    op.drop_column('attachments', 'wheel_set_id', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_expenses_vehicle_id'), table_name='vehicle_expenses', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_expenses_trip_id'), table_name='vehicle_expenses', schema='fleet')
    op.drop_index(op.f('ix_fleet_vehicle_expenses_expense_date'), table_name='vehicle_expenses', schema='fleet')
    op.drop_table('vehicle_expenses', schema='fleet')
    op.drop_index('uq_fleet_wheel_fitments_one_active_per_vehicle', table_name='wheel_fitments', schema='fleet', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_fleet_wheel_fitments_wheel_set_id'), table_name='wheel_fitments', schema='fleet')
    op.drop_index(op.f('ix_fleet_wheel_fitments_vehicle_id'), table_name='wheel_fitments', schema='fleet')
    op.drop_table('wheel_fitments', schema='fleet')
    op.drop_index(op.f('ix_fleet_wheel_sets_vehicle_id'), table_name='wheel_sets', schema='fleet')
    op.drop_table('wheel_sets', schema='fleet')
    # ### end Alembic commands ###
